# Setup
title:               Higashi.blog
tagline:             'Random notes on cryptography and engineering'
description:         "<a href='https://www.linkedin.com/in/steven-dongze-yue/'>Steven (Dongze) Yue's</a> personal blog."
url:                 https://higashi.blog
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Steven Dongze Yue
  url:               https://twitter.com/StevenYue13
  email:             dy85@cornell.edu

# Gems
plugins:
  - jekyll-paginate
  - jekyll-mermaid

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid@10.4.0/dist/mermaid.min.js'
